version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
            test: ["CMD", "pg_isready", "-q"]
            timeout: 60s
            retries: 10

  backend:
    image: oskalis/foodgram_backend:latest
    restart: always
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db:
            condition: service_healthy

  frontend:
    image: oskalis/foodgram_frontend:latest
    restart: always
    env_file: .env
    volumes:
      - ../frontend/:/app/result_build/

  gateway:
    image: oskalis/foodgram_gateway
    restart: always
    ports:
      - 9009:80
    volumes:
      # - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - db
      - backend
      - frontend
